#! /bin/bash

STUDENT_FRONT="sudo docker run -it --name"
SLAVE_COMMAND=""
COMMAND_LAST="sungsu7437/ubuntu_hadoop /bin/bash"
SLAVE="slave"
ADDHOST='--add-host='
IP="10.0.0."
STUDENTIP="10.0.0.10"
i=1
j=1
k=2

if [[ -z "$4" ]]; then
	echo "format is wrong"
	echo "./add_studnet network-name student-from student-to number-of-hosts"
	echo "ex) ./add_student my-net 1 5 10"
	echo "network is my-net, student from 1, student to 5, number of hosts=10"
	exit 0
fi
	

i=$2
while [ $i != $(($3+1)) ];
do
	SLAVE_COMMAND="$STUDENT_FRONT student$i --network $1 --ip $STUDENTIP$i --add-host=master:10.0.0.2"
	j=1
	while [ $j != $4 ];
	do
        	SLAVE_COMMAND="$SLAVE_COMMAND $ADDHOST$SLAVE$j:$IP$(($j+2))"
       		j=$(($j+1))
	done
	$SLAVE_COMMAND -p 2200$k:2200$k --storage-opt size=500G $COMMAND_LAST
	SLAVE_COMMAND=''
	i=$(($i+1))
	k=$(($k+1))
done

