#! /bin/bash

NETWORK=$2

MASTER_COMMAND="sudo docker run -it --name master --network $1 --ip 10.0.0.2 -p 8088:8088 -p 8042:8042 -p 8085:8080 -p 4040:4040 -p 7077:7077 -p 2022:22 --add-host=master:10.0.0.2 --cpuset-cpus=0,1,2,3 --memory 12g"
SLAVE_FRONT="sudo docker run -it --name"
SLAVE_COMMAND=""
COMMAND_LAST="sungsu7437/ubuntu_hadoop /bin/bash"
SLAVE="slave"
ADDHOST='--add-host='
IP="10.0.0."

numOfContainers=1
numOfAddHosts=1
numOfCores=1
coreNumber=1
if [[ -z "$5" ]]; then
	echo "format is wrong"
	echo "./run_hadoop network-name want-master slave-from slave-to number-of-hosts"
	echo "ex) ./run_hadoop my-net 1 1 5 10"
	echo "network is my-net, need master container, slave from 1, slave to 5, number of hosts=10"
	exit 0
fi
	


if [ $2 == 1 ]; then
	while [ $numOfAddHosts != $(($5+1)) ];
	do
		MASTER_COMMAND="$MASTER_COMMAND $ADDHOST$SLAVE$numOfAddHosts:$IP$(($numOfAddHosts+2))"
		numOfAddHosts=$(($numOfAddHosts+1))
	done
	MASTER_COMMAND="$MASTER_COMMAND $COMMAND_LAST"
	$MASTER_COMMAND
fi

numOfContainers=$3
while [ $numOfContainers != $(($4+1)) ];
do
	SLAVE_COMMAND="$SLAVE_FRONT slave$numOfContainers --network $1 --ip $IP$(($numOfContainers+2)) --memory 6g --storage-opt size=300G --add-host=master:10.0.0.2"
	numOfAddHosts=1
	while [ $numOfAddHosts != $(($5+1)) ];
	do
        	SLAVE_COMMAND="$SLAVE_COMMAND $ADDHOST$SLAVE$numOfAddHosts:$IP$(($numOfAddHosts+2))"
       		numOfAddHosts=$(($numOfAddHosts+1))
	done

        numOfCores=1
	if [ $2 == 1 ]; then
		SLAVE_COMMAND="$SLAVE_COMMAND --cpuset-cpus=$(($(($(($coreNumber-1))*3))+4))"
       		while [ $numOfCores != 3 ];
        	do
                	SLAVE_COMMAND="$SLAVE_COMMAND,$(($(($(($(($coreNumber-1))*3))+4))+$numOfCores))"
                	numOfCores=$(($numOfCores+1))
        	done
	else
		SLAVE_COMMAND="$SLAVE_COMMAND --cpuset-cpus=$(($(($coreNumber-1))*3))"
                while [ $numOfCores != 3 ];
                do
                        SLAVE_COMMAND="$SLAVE_COMMAND,$(($(($(($coreNumber-1))*3))+$numOfCores))"
                        numOfCores=$(($numOfCores+1))
                done
	fi
	
	$SLAVE_COMMAND $COMMAND_LAST
	SLAVE_COMMAND=''
	numOfContainers=$(($numOfContainers+1))
	coreNumber=$(($coreNumber+1))
done


